// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfnGcSr2OIujpuQrx_A1bNfguf0lFYQlk',
    appId: '1:873679637512:web:85759c5d829060c1f395bd',
    messagingSenderId: '873679637512',
    projectId: 'coincollector-59b5b',
    authDomain: 'coincollector-59b5b.firebaseapp.com',
    storageBucket: 'coincollector-59b5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZI8ij34iiPv49S9kQK1xG9x2dsIm-Gw',
    appId: '1:873679637512:android:54acaea93c3851fef395bd',
    messagingSenderId: '873679637512',
    projectId: 'coincollector-59b5b',
    storageBucket: 'coincollector-59b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAtzC-qGgQ-Z6ItU_SZLj8MfLAnnlMb0c',
    appId: '1:873679637512:ios:5ec02251f6757543f395bd',
    messagingSenderId: '873679637512',
    projectId: 'coincollector-59b5b',
    storageBucket: 'coincollector-59b5b.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfnGcSr2OIujpuQrx_A1bNfguf0lFYQlk',
    appId: '1:873679637512:web:6cf33a110efec08bf395bd',
    messagingSenderId: '873679637512',
    projectId: 'coincollector-59b5b',
    authDomain: 'coincollector-59b5b.firebaseapp.com',
    storageBucket: 'coincollector-59b5b.appspot.com',
  );
}
